### ISSUE TITLE
Required gstreamer plugin 'srtp' not found

### ISSUE THREAD

**Issue by activedecay** [centricular/gstwebrtc-demos#118]
I built gstreamer from source on Ubuntu 16.04

after building the sendrecv/gst/webrtc-sendrecv.c program, executing it results in an error

    Required gstreamer plugin 'srtp' not found

There doesn't seem to be an 'srtp' plugin on this page https://gstreamer.freedesktop.org/documentation/plugins_doc.html?gi-language=c

Is there a simple solution that I'm missing?

**Comment by sdroege** [comment]
You need the `srtp` plugin (and various others) from `gst-plugins-bad`. It's apparently not part of your build results and because of that not found by the application.

Check the output of `configure` (or `meson`) of `gst-plugins-bad` to see why it was not built, you're probably missing the development package for `libsrtp`.
