### ISSUE TITLE
InvalidStateError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Called in wrong state: stable

### ISSUE THREAD

**Issue by Miltosh** [centricular/gstwebrtc-demos#231]
When i'm try connect to https://webrtc.nirbheek.in/ and send generated id, get next error:

> InvalidStateError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Called in wrong state: stable

It happens if I'm use Google Chrome, if I'm use Mozilla Firefox, error looks like this:

> InvalidStateError: Cannot set remote answer in state stable

**Comment by ystreet** [comment]
This is not enough information to be able to debug.  One would need at least some GStreamer debug logging with e.g. the attempted exchanged SDP's.  This may also be due to browser configurations possibly imposed by linux distributions.

These examples have moved to https://gitlab.freedesktop.org/gstreamer/gst-examples/-/tree/master/webrtc.
