### ISSUE TITLE
Can it do recording to a file?

### ISSUE THREAD

**Issue by thehappycoder** [centricular/gstwebrtc-demos#3]
I tried using ffmpeg (which had SDP file as an input) to record live webrtc stream and it worked OK. There were some problems though.

I got interested in gstwebrtc in hope it would be better but since there is no documentation, it's very hard to even try it out.

I wonder if recording be done by gstreamer CLI alone or I would have to write C code?

**Comment by ystreet** [comment]
webrtcbin (the GStreamer element used by these examples) doesn't define the signalling layer (how to transfer the sdp or ice candidates, etc between peers) because that part is application specific in the WebRTC specification.  As a result, such signalling needs to be adapted for every service you want to interact with and some code does need to be written for this purpose.  @nirbheek wrote a [blog post](http://blog.nirbheek.in/2018/02/gstreamer-webrtc.html) that has some of the requirements for hooking into the various signals in webrtcbin to perform this task.

It's also possible to write wrapper GStreamer elements around webrtcbin to perform the signalling in a gst-launch pipeline if that would more suitable to your use case and I have done that in the past (no public code/examples though).

Alternatively, if you already have an SDP, there is another GStreamer element called sdpdemux that would probably be equivalent to your existing ffmpeg based solution.

Once you have the streams, recording to file is plugging the necessary muxers and filesink common to any encoding pipeline.

**Comment by sdroege** [comment]
Note also that you don't necessarily have to write code in C. Any language with GStreamer bindings (and updated for the new GStreamer core API) should do the job, e.g. Python.

**Comment by thehappycoder** [comment]
Where could I find more documentation on the sdpdemux? Can't get it to work, unfortunately.

This is what I get:
```
gst-launch-1.0 -v filesrc location=file.sdp ! sdpdemux ! fakesink
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
ERROR: from element /GstPipeline:pipeline0/GstSDPDemux:sdpdemux0: Could not determine type of stream.
Additional debug info:
gstsdpdemux.c(1195): gst_sdp_demux_start (): /GstPipeline:pipeline0/GstSDPDemux:sdpdemux0:
Could not create RTP session manager.
ERROR: pipeline doesn't want to preroll.
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...
```

And here is file.sdp:
```
v=0
o=- 0 0 IN IP4 127.0.0.1
s=-
c=IN IP4 127.0.0.1
t=0 0
m=video 40297 RTP/AVP 101
a=rtpmap:101 VP8/90000
a=recvonly
```

Note: ffmpeg works fine with this sdp file

**Comment by thehappycoder** [comment]
Oh, looks like it's because I didn't install `gst-plugins-good`

**Comment by thehappycoder** [comment]
OK, I got it working but is there a way for gstreamer to determine manually whether it should use `rtpvp8depay ! h264parse` or `rtpvp8depay`?

For h.264
```
gst-launch-1.0 -v fdsrc ! sdpdemux ! rtpjitterbuffer ! rtph264depay ! h264parse ! matroskamux ! filesink location=file.mkv
```

For vp8:
```
gst-launch-1.0 -v fdsrc ! sdpdemux ! rtpjitterbuffer ! rtpvp8depay ! matroskamux ! filesink location=file.mkv
```

**Comment by tp-m** [comment]
There's a `parsebin` element, which is like `decodebin` but without the decoding step.

**Comment by sdroege** [comment]
This is also all unrelated to webrtcbin, better to discuss this on the mailing list https://lists.freedesktop.org/mailman/listinfo/gstreamer-devel

**Comment by thehappycoder** [comment]
@tp-m parsebin did the job!

Thanks, guys! I will subscribe to gstreamer-devel.

In case someone googles this page, here is what I came up so far (typescript code):
```
const command = `echo "${sdp}" | gst-launch-1.0 -v fdsrc ! sdpdemux latency=10000 timeout=0 ! parsebin ! matroskamux streamable=false ! filesink location=${outputPath}`
```
