### ISSUE TITLE
Raspberry plugin nice not found

### ISSUE THREAD

**Issue by gkslsahin** [centricular/gstwebrtc-demos#53]
I build gstreamer with this instructions https://gist.github.com/Swap-File/d8511128930c93281f36f18d634f6748
I  compiled the webrtc-sendrecv.c and when i run webrtc-sendrecv i get the error

> Required gstreamer plugin 'nice' not found
> Required gstreamer plugin 'webrtc' not found

gst-launch-1.0 --version
> gst-launch-1.0 version 1.14.3
> GStreamer 1.10.4
> Unknown package origin

**Comment by ykazakov** [comment]
You need to compile them additionally.
See my modified instructions (for GStreamer without X)
https://gist.github.com/ykazakov/472a46e3838bf9259921b273ca8a0173

**Comment by satoyoshiharu** [comment]
I build Gstreamer 1.15.0 by gst-uninstalled (https://arunraghavan.net/2014/07/quick-start-guide-to-gst-uninstalled-1-x/) on Ubuntu.
I tried to run "python3 webrtc-sendrecv.py ID" but found an error of 'nice' and 'srtp' pulg-ins missing.
I don't find those in the plugin list on official Gstreamer web side.
Can the above script solve my issue?

**Comment by ystreet** [comment]
The nice and srtp plugins have external dependencies on libnice and libsrtp respectively.  Install those deps and then rebuild GStreamer.

**Comment by gkslsahin** [comment]
If the version of external dependencies is old, these plugins will not be installed. You can check the configure.log. The versions of these dependencies may be old, so you may need to build them.

**Comment by satoyoshiharu** [comment]
Thank you for comments, and the script.

I tried https://gist.github.com/ykazakov/472a46e3838bf9259921b273ca8a0173 on a clean Ubuntu18.04 LTS Virtual Machine. 
I found that "apt-get install" cannot find three packages: libdiac-dev, libschroedinger-dev, and libslv2-dev packages. 
Are those critical?

I commented out those and proceed the scripts anyway. 
But I failed to build webrtcbin. 
The build log includes a lot of warnings to tell that the /opt/vc/include folder and the files under this are missing.  
It looks those warnings blocks building a number of plugins.
Any work-around?
does vc means visual c? Visual Studio Code is required environment?

**Comment by ystreet** [comment]
vc is VideoCore and is the the GPU/display controller on the rpi.

If you want fast OpenGL output, then you also need to build gst-plugins-base against dispmanx/VideoCore, EGL, GLES2 as well instead of the software-based X11 path.

**Comment by satoyoshiharu** [comment]
I want to build webrtcbin on Ubuntu as well as RPI eventually, but my first experiment of using webrtcbin is on Ubuntu desktop. I don't really care for now whitchever X11-based or VideoCore is used.

>build gst-plugins-base against dispmanx/VideoCore, EGL, GLES2

How to do this? Any clues about how to solve the "/opt/vc/include" missing errors?

**Comment by ystreet** [comment]
Are the errors from gst-omx?  If so, you don't need gst-omx on a regular Ubuntu desktop.

**Comment by satoyoshiharu** [comment]
The errors are from many plugins including webrtcbin.
I modified https://gist.github.com/ykazakov/472a46e3838bf9259921b273ca8a0173 so that any packages uses usual configure, make, checkinstall, and don't use "LDFLAGS=..." which may not needed on Ubuntu. Now compilation and linking succeeds and /usr/lib/gstreamer-1.0 includes expected files which includes webrtc, nice, srtp..  However "gst-inspect-1.0 webrtcbin" doesn't show up webrtcbin,... The "export GST_PLUGIN_PATH=/usr/lib/gstreamer-1.0/" have gst-inspect-1.0 find them. But I face "so" load time errors. i will consult in other places .

**Comment by dayjaby** [comment]
Why is this closed? The issue is not resolved yet.

**Comment by ystreet** [comment]
This is closed because this is an environment setup issue.  These demos need the nice/dtls/srtp plugins from GStreamer itself.  If your distro does not provide those plugins, talk to the distribution.  If you are compiling GStreamer yourself, then you need to ensure that those plugins are built and available.  There is nothing that these demos can do to fix issues of plugins missing from a GStreamer installation.
