### ISSUE TITLE
data_channel seems closed

### ISSUE THREAD

**Issue by turtlebond** [centricular/gstwebrtc-demos#55]
Trying the example for data channel I am getting this error:
** (webrtc-sendrecv:10908): CRITICAL **: gst_webrtc_bin_create_data_channel: assertion 'webrtc->priv->is_closed != TRUE' failed
Could not create data channel, is usrsctp available?

Configuring and making gst_plugins_bad can see usrsctp is present.
**config.log**
```
USRSCTP_LIBS='-lusrsctp'
ac_cv_header_usrsctp_h=yes
ac_cv_lib_usrsctp_usrsctp_init=yes
```

Get and build the gstreamer,gst-plugins-base and gsd-plugins-bad  - v1.15.
Where could I have done wrong?

Thank you.

**Comment by turtlebond** [comment]
Tried compiling with libusrsctp and gstreamer-sctp but no success
**Makefile**
`LIBS	:= $(shell pkg-config --libs --cflags gstreamer-webrtc-1.0 gstreamer-sdp-1.0 libsoup-2.4 gstreamer-sctp-1.0 json-glib-1.0) -lusrsctp`

**Comment by peebles** [comment]
Ditto.  Baffling.

Before I got `ac_cv_header_usrsctp_h=yes`, I had to get and build (for Rpi3):

```sh
git clone https://github.com/sctplab/usrsctp
cd usrsctp
./bootstrap
./configure --prefix /usr/ --libdir /usr/lib/arm-linux-gnueabihf/
make
sudo make install
```
The only thing in the gstreamer build that links with libusrsctp is `gst-plugins-bad/ext/sctp`, which gets installed into "/usr/local/lib/gstreamer-1.0/libgstsctp.so.0.0.0".

**Comment by a-morales** [comment]
~~Any updates on this? I've built GStreamer from HEAD as well as `gst-plugins-base` and `gst-plugins-bad` and I'm still encountering the same issue.~~

Disregard, I posted after not refreshing and not seeing the commit closing this issue. Running on latest from `master` and data channels work.

**Comment by introrse** [comment]
I still saw this closed data channel on a fresh install of gstreamer 1.15.1 (on OS/X).  

I then tried rebuilding from `master` on Linux, and made absolutely sure all deps were there.  The gstreamer sctp parts and gstreamer in general built without error, but I got a missing file error for libgstsctp-1.0.la when building the sendrecv demo program.

It seems that, at least for me and on that linux install, pkg-config handles `gstreamer-sctp-1.0` incorrectly.  Perhaps this is due to some problem in my uninstalled build config, though I think I just followed instructions.  Anyway, pkg-config adds the libgstsctp-1.0.la file to the gcc command line (not a -l reference, but the filename) and uses a path where .la file doesn't even exist.  Grabbing the .la file from elsewhere and locating it as indicated just leads gcc to complain about the format of the file. (understandably)

The solution I found was to remove the sendrecv makefile's reference to `gstreamer-sctp-1.0` and add a manually composed libpath and library reference to the end of the LIBS line: `-L <path to gst-build>/build/subprojects/gst-plugins-bad/gst-libs/gst/sctp -lgstsctp-1.0`

__Hooray:  A functional data channel in the sendrecv demo!__

(Backporting the makefile change to my Mac didn't fix the error there, so it seems likely 1.15.1 is missing whatever patches fixed the data channel support. The commit ystreet references in the sendrecv demo above is present in the code I was trying to use, so that's not what's missing)

**Comment by sampleref** [comment]
For GStreamer version >=1.16 it works but webrtcbin has to be put in state READY first,

_gst_element_set_state (webrtc1, **GST_STATE_READY**);
g_signal_emit_by_name(webrtc1, "create-data-channel", "channel", NULL,
                          &send_channel);_

As mentioned at https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/issues/992

**Comment by razvanphp** [comment]
if somebody has this error in their DEBUG log:
```
WARN webrtcbin gstwebrtcbin.c:135:_have_sctp_elements:<sendonly> error: sctp elements are not available
```
on OSX you need to install from source:
```
brew install libusrsctp
brew reinstall gst-plugins-bad -s
```
