### ISSUE TITLE
changing video size?

### ISSUE THREAD

**Issue by ghost** [centricular/gstwebrtc-demos#6]
when receiving a video the video goes from 800x600 to 640x480 to 320x240. ive only tried the demo, not sure what the problem is

**Comment by nirbheek** [comment]
What sort of setup do you have? Are you testing this over localhost or over the internet?

My first thought would be that your browser is deciding for some reason that your network link can't keep up with the video bitrate and is scaling the video down to reduce the bitrate.

**Comment by ghost** [comment]
i have been testing things online and using webrtc.nirbheek.in. maybe its my browser/connection since you aren't having the problem. i can try debugging again when i have a more stable internet connection. my solution was to make the video constraints 320x240 and so i havent had the issue

also would adding a H.264 encoder to the pipeline make Safari compatible?

great demo

**Comment by nirbheek** [comment]
> i have been testing things online and using webrtc.nirbheek.in. maybe its my browser/connection since you aren't having the problem.

If both the gst code and the browser are on the same machine, the audio and video are sent over loopback and do not go over the internet at all, so that might not be the problem.

Using h.264 instead of vp8 is the important step in making the example compatible with Safari, but there might be other quirks that we are missing since every browser seems to have its own quirks.

Have you been doing all testing on macOS?

**Comment by nirbheek** [comment]
This was same as https://github.com/centricular/gstwebrtc-demos/issues/11, which is fixed. Closing.
