### ISSUE TITLE
TypeError: 'Structure' object is not subscriptable

### ISSUE THREAD

**Issue by satoyoshiharu** [centricular/gstwebrtc-demos#69]
I run the sample as below on Ubuntu 18.10 (latest non-LTS) which includes Gstreamer 1.14.4. 
I sudo apt-get install gstreamer1.0-plugins-bad etc (a lot).
I clicked https://webrtc.nirbheek.in with browser on another PC to get ID, and run 
python3 webrtc-sendrecv.py the-ID.
But I found the following errors.
Could someone tell me what I miss?

Traceback (most recent call last):
  File "webrtc-sendrecv.py", line 53, in on_offer_created
    offer = reply['offer']
TypeError: 'Structure' object is not subscriptable

I remember I found the same error when used Gst_uninstalled tool with Ubuntus 18.04 LTS, and I gave up to use uninstalled tool. The problem looks like a timing issue around variable instantiation of sample codes.

**Comment by riccardocagnasso** [comment]
Bump, I came across this bug too.

It did that on one computer with one archlinux installation and not on another without a different archlinux installation. Since the machine with the bug was a testing machine I simply copied the content of / from the machine that was working on the machine that was not. Elegant, I know. 

But this means that is something related to the environment. Some library missing or something like that. You can reproduce it by running sendrecv on a freshly installed antergos system.

**Comment by thaytan** [comment]
This happens when you have the python gobject-introspection wrapper (which lets you import the GStreamer binding) but not the python-gstreamer module that provides customisations to the bindings to make them more pythonic. Make sure you have the appropriate version of gst-python (under whatever the package is called on your distro) that matches your python version.
